### ISSUE TITLE
On F-droid, the changelog link return a GitHub 404.

### ISSUE THREAD

**Issue by quasipedia** [holylobster/nuntius-android#26]
As per title, when trying to click on the changelog from the upgrade panel, it returns 404.

**Comment by Kurtpenter** [comment]
Thanks, I reported the problem to the F-Droid staff: https://f-droid.org/forums/topic/nuntius/

**Comment by nacho** [comment]
This seems fixed now.

**Comment by quasipedia** [comment]
@nacho - Indeed! Thanks! :metal:
