### ISSUE TITLE
Add to F-Droid repo

### ISSUE THREAD

**Issue by Susurrus** [holylobster/nuntius-android#3]
I don't have Google Play Store installed on my Android phone and don't plan on installing it. I do, however, use F-Droid. Since I didn't see a link to download the .apk, it'd be great to get this into F-Droid so I can install it through there.

**Comment by Kurtpenter** [comment]
Thanks for the report. I had a quick look here:
 - https://f-droid.org/contribute/
 - https://f-droid.org/manual/fdroid.html#Importing-Applications
 - https://f-droid.org/forums/forum/submission-queue/

It is not top priority but we can definitely do it.

If you are familiar with fdroid command and want to help, you can try to run it as suggested with:
 ./fdroid import --url=https://github.com/holylobster/nuntius-android

Then attach the output to this issue (or create a pull request),  we'll fill the blanks :)

**Comment by Susurrus** [comment]
Looks like someone beat me to it: https://f-droid.org/forums/topic/nuntius/
