### ISSUE TITLE
Some Spanish, French and Slovak translations are missing

### ISSUE THREAD

**Issue by Kurtpenter** [holylobster/nuntius-android#36]
Error:(20) Error: "version" is not translated in "es" (Spanish), "fr" (French), "sk" (Slovak) [MissingTranslation]
Error:(21) Error: "app_blacklist_title" is not translated in "es" (Spanish), "fr" (French) [MissingTranslation]
Error:(22) Error: "app_blacklist_summary" is not translated in "es" (Spanish), "fr" (French) [MissingTranslation]
Error:(23) Error: "blacklisted_title" is not translated in "es" (Spanish), "fr" (French) [MissingTranslation]
Error:(24) Error: "blacklist_title" is not translated in "es" (Spanish), "fr" (French) [MissingTranslation]
Error:(25) Error: "added_to_blacklist" is not translated in "es" (Spanish), "fr" (French) [MissingTranslation]
Error:(26) Error: "removed_from_blacklist" is not translated in "es" (Spanish), "fr" (French) [MissingTranslation]
Error:(27) Error: "undo" is not translated in "es" (Spanish), "fr" (French) [MissingTranslation]

**Comment by nacho** [comment]
Pointing to @leo666 @prescott66

**Comment by prescott66** [comment]
fixed. thx
