### ISSUE TITLE
Podcast player notification keeps poping upp all the time

### ISSUE THREAD

**Issue by snaggen** [holylobster/nuntius-android#8]
Playing a podcast using Podcast Addict, will pop upp a notification every 5-10 seconds. The cause is probably due to the notification being persistant and getting updated with playing progress. So I suggest you just ignore ongoing notifications, or keep track of them and just show the notification once.

**Comment by Kurtpenter** [comment]
Hi snaggen, thanks for the report, the problem is clear are we are working on it... stay tuned... :)

**Comment by Kurtpenter** [comment]
Fix committed ad49d27b3d70d68e7acbcea9efd2b74fa7516ebb , will be in next release (1.0.2)

**Comment by Kurtpenter** [comment]
Hi snaggen, we released version 1.0.2 which should fix the issue. In case you still see the problem reopen the issue. Thanks!
